name: Daily News Summary

on:
  schedule:
    # Runs at 7:00 AM UTC daily
    - cron: '0 7 * * *'

  # Allows manual trigger via the Actions tab
  workflow_dispatch:

jobs:
  run-news-script:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python 3.x
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'  # Specify the Python version, like 3.9

      # Step 3: Install FFmpeg (required for pydub)
      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 gtts schedule pydub

      # Step 5: Run the Python script
      - name: Run Python script
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: |
          python news_summary.py
